## Use the official .NET Core SDK image version 7.0 as the build environment
#FROM mcr.microsoft.com/dotnet/aspnet:7.0
#
## Copy everything
#COPY ./app
#WORKDIR /app
## Restore as distinct layers
#RUN dotnet publish -c Release -o out
#